### ISSUE TITLE
Extend to N2H+ fitting

### ISSUE THREAD

**Issue by jcaza02** [mcyc/mufasa#29]
Add N2H+ model and allow for choice between N2H+ or NH3 model when fitting

**Comment by mcyc** [comment]
I think we can start by adding an `n2hp.py` file to the `spec_models` folder.

**Comment by mcyc** [comment]
Let's modularize model registration with a new function called `register_model()` in `multi_v_fit.py` that accepts an argument `fittype` for different spectral models.

The `register_model()` can replace lines such as the ones below:
https://github.com/mcyc/mufasa/blob/b105896792f346821ba2872fe9233d0cb49f538b/mufasa/multi_v_fit.py#L594

**Comment by mcyc** [comment]
@jcaza02, the following placeholder (from commit c219fd225016b99adc41bd5761642e6022226e7b) should be ready for you to insert your n2h+ models. 

https://github.com/mcyc/mufasa/blob/c219fd225016b99adc41bd5761642e6022226e7b/mufasa/multi_v_fit.py#L59-L62
