### ISSUE TITLE
Make MUFASA python 3.11 compatible 

### ISSUE THREAD

**Issue by mcyc** [mcyc/mufasa#40]
MUFASA may not currently be python 3.11 compatible

**Comment by taiwithers** [comment]
I've been running it on 3.11 and haven't had issues. I am running my own fork [multicore_options](https://github.com/taiwithers/mufasa/tree/multicore_options) which I haven't changed in quite a while, so I'm not sure exactly what changes were made

**Comment by mcyc** [comment]
The changes made so far aren't Python 3.11 specific, and it looks like it's
the other packages that are causing issues. I'm investigating them at the
moment. By the way, which version of pyspeckit are you using?

**Comment by taiwithers** [comment]
For pyspeckit I'm also using a personal [fork](https://github.com/taiwithers/pyspeckit) - though it looks like there have been upstream changes, I'll need to go through those at some point and see if I can pull any of them down

**Comment by mcyc** [comment]
Okay, it looks like you have been running into the same pyspeckit issues
I've been running into as well. I'm looking deeper into what the root cause
may have been

**Comment by mcyc** [comment]
@taiwithers, I've made a pull request ([413](https://github.com/pyspeckit/pyspeckit/pull/413)) from my own [fork](https://github.com/mcyc/pyspeckit/tree/master) to pyspeckit to resolve at least one of the issues you've encountered.

**Comment by mcyc** [comment]
@taiwithers, my pull requests for the bug fixes have been accepted by [pyspeckit](https://github.com/pyspeckit/pyspeckit) and [FITS_tools](https://github.com/keflavich/FITS_tools). You can pull the latest version from their GitHub repos and run them installed if you like
