### ISSUE TITLE
Import error for collections Iterable

### ISSUE THREAD

**Issue by taiwithers** [mcyc/mufasa#7]
Python 3.3+ requires importing collections.abc rather than collections [`documentation`](https://docs.python.org/3/library/collections.abc.html)

UltraCube.py line 97 has `from collections import Iterable`

The Py3 compatible version should say `from collections.abc import Iterable`

**Comment by mcyc** [comment]
A change to [line 97](https://github.com/mcyc/mufasa/blob/964f93d4d83ca05e606ac60870b378a67bc2de7a/mufasa/UltraCube.py#L96) has been made accordingly in commit b110c62f2ed012c53071643a7172153e41737957.
