### ISSUE TITLE
Bug(s) in refit_2comp_wide

### ISSUE THREAD

**Issue by mcyc** [mcyc/mufasa#90]
`refit_2comp_wide()` in `master_fitter.py` is currently not selecting the correct model and replacing the right pixels.

**Comment by taiwithers** [comment]
Is this a bug introduced in a recent patch on the main branch, or is this a potentially long-lived issue?

**Comment by mcyc** [comment]
It may have been introduced a while back, unfortunately. It only became apparent to me in recent updates, where MUFASA tries to refit pixels more aggressively. 

With any luck, I'm hoping to get a patch out next week.

**Comment by mcyc** [comment]
I'm testing the `main` branch right now and will post updates here as I go.

**Comment by mcyc** [comment]
It looks like the latest patches already applied to the `main` branch were able to fix most of the issue. The success rate for two-component fits seem a little less than it was before, and I'll continue to look into that.

**Comment by mcyc** [comment]
I've merged some changes to `main` to ensure the refitting results are updated and saved correctly. By default, the main refitting functions in `master_fitter.py` now save the new results automatically.

I'll tweak the refitting functions further to see if I can improve their fitting accuracy. I'll also run a few more tests to make sure the bugs are all dealt with.

**Comment by mcyc** [comment]
Okay, it looks like the refitting methods are back in good working order now, perhaps even more efficient than before. The `main` branch since the https://github.com/mcyc/mufasa/pull/114 merge seems to be working well under `Python 3.12`.

@taiwithers, a bug I caught while working on this may have been around for as long as you've used `MUFASA`. It only affects the refitted pixels, but if the original and the new fits are sufficiently different, the relative likelihood (ln _k_) being calculated between the replacement 2-component model and the 1-component (and noise) model can be fairly incorrect. This is due to the AICc re-calculation failing to adopt the updated spectral mask needed to properly perform the model comparison. 

For the `master_2comp_fit` method, this means the pixels replaced by `refit_bad_2comp` are correct, but its ln _k_ values calculated afterward are incorrect, unless you reload the fits from the saved files and re-calculate again. The pixels subsequently replaced by `refit_2comp_wide` should also be correctly selected, but the initial refitting selection may be wrong for pixels that have already been replaced once. In short, any pixel that was replaced would have had an inaccurate ln _k_ value unless these calculations was done from scratch again. This may have partially explained why you've seen `MUFASA` failing to recover obvious 2-component spectra with wide velocity separation. 

Luckily, `save_best_2comp_fit` was designed from the beginning to isolate these kinds of bugs, and the final ln _k_ maps saved from it were correct. This particular bug ultimately means `MUFASA` was missing pixels it should've attempted to refit beyond its initial refit attempt. The bug, however, wouldn't have caused issues if the subsequent refitting was done in a new session by reloading the previous fits first via a new instance of `UltraCube`.

The `refit_2comp_wide` still isn't operating optimally at recovering wide-seperating compoents, but I'll address that in a different issue.

**Comment by taiwithers** [comment]
Okay so just to confirm, this sounds like anything that was using `refit_2comp_wide` and `refit_bad_2comp` should be re-run?

**Comment by mcyc** [comment]
Yeah, I would recommend rerunning `refit_2comp_wide` and `refit_bad_2comp`, but not `iter_2comp_fit`. This should save a lot of time since refitting is typically only needed over relatively smaller fraction of the pixels.
